Repository QAZIMAAZARSHAD/Voters-Registration-Portal, pull requests merged in 2021-06, with the labels that each got.

#76 Made Website Completely Responsive
  Style.css
  index.html
Labels: LGMSOC21, 🟥 Level4

#70 Preloader
  .vscode/settings.json
  Style.css
  index.html
Labels: LGMSOC21, 🟨 Level2

#84 Supported docs dropdown added
  Home.html
Labels: LGMSOC21, 🟩 Level1

#91 Update Style.css
  Style.css
Labels: LGMSOC21, 🟩 Level1

#94 Update README.md
  README.md
Labels: LGMSOC21, 🟩 Level1

#88 Added a help section page
  Home.html
  help.css
  help.html
Labels: LGMSOC21, 🟨 Level2

#74 Update issue template
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: LGMSOC21, 🟪 Level0

#66 Improved screenshot in README
  Images/snapshot.png
  README.md
Labels: LGMSOC21, 🟪 Level0

#118 Updated Copyright Year
  Home.html
  home_hindi.html
  index.html
Labels: LGMSOC21, 🟩 Level1

#115 adjust zoom and language button
  Home.html
  home_hindi.html
  index.html
Labels: LGMSOC21, 🟩 Level1

#113 Pin code autofills state & district
  Home.html
  home_hindi.html
Labels: LGMSOC21, 🟥 Level4

#127 logo
  logo.png
  logo2.png
Labels: LGMSOC21, 🟪 Level0

#131 Made Captcha Functionable
  Home.html
  home_hindi.html
  js/video.js
Labels: LGMSOC21, 🟧 Level3

#129 changed distrcits dropdown
  Home.html
Labels: LGMSOC21, 🟧 Level3

#114 Display uploaded documents
  Home.html
  home_hindi.html
Labels: LGMSOC21, 🟧 Level3

#133 Add hover effect on tiranga image
  Home.html
  Style.css
  help.css
  help.html
  home_hindi.html
  index.html
Labels: LGMSOC21, 🟩 Level1

#134 Feature added on Submit Button click
  Home.html
Labels: LGMSOC21, 🟪 Level0

#138 Make Zoom In/Out Functionable
  Home.html
  Style.css
  home_hindi.html
  index.html
  js/video.js
Labels: LGMSOC21, 🟧 Level3

#147 Hover effect on help desk button added
  Home.html
  Style.css
  home_hindi.html
Labels: LGMSOC21, 🟩 Level1

#148 Update Home.html with reference to issue #146
  Home.html
Labels: LGMSOC21, 🟪 Level0

#149 Added Custom scrollbar
  Style.css
  help.css
  help.html
  home_hindi.html
Labels: LGMSOC21, 🟨 Level2

#152 Corrected Date of Birth format
  Home.html
  home_hindi.html
Labels: LGMSOC21, 🟪 Level0

#153 Added space in b/w overlapping fields
  Home.html
  Style.css
Labels: LGMSOC21, 🟪 Level0

#156 Corrected spelling mistake
  Home.html
Labels: LGMSOC21, 🟪 Level0

#158 Title logo
  Home.html
  help.html
  index.html
Labels: LGMSOC21, 🟪 Level0

#162 Update README.md with reference to issue #161
  README.md
Labels: LGMSOC21, 🟪 Level0

#164 Added Login and signup page with form validation
  Images/voting-img.jpg
  Images/voting.jpg
  Style.css
  index.html
  login.html
  sign-up.html
Labels: LGMSOC21, 🟥 Level4

#166 Update home.html with reference to issue #165
  Home.html
Labels: LGMSOC21, 🟪 Level0

#170 Audio recaptcha added
  Home.html
Labels: LGMSOC21, 🟥 Level4

#171 updated the light dark mode
  Home.html
  Style.css
  help.css
  help.html
  index.html
  login.html
  sign-up.html
Labels: LGMSOC21, 🟧 Level3

#177 Add issue #168 to main
  Style.css
Labels: LGMSOC21, 🟪 Level0

#185 Show/hide pwd toogle
  login.html
  sign-up.html
Labels: LGMSOC21, 🟨 Level2

#189 scrolltotop
  Home.html
  Style.css
  help.html
  index.html
  login.html
  sign-up.html
Labels: LGMSOC21, 🟨 Level2

#200 Made entire start button clickable
  index.html
Labels: LGMSOC21, 🟩 Level1

#202 PR against issue #181 Replace header Image
  Home.html
  Style.css
  forgetPass.html
  help.css
  help.html
  index.html
  login.html
  sign-up.html
Labels: LGMSOC21, 🟩 Level1

#206 Favicon added
  Home.html
  forgetPass.html
  help.html
  index.html
  login.html
  sign-up.html
Labels: LGMSOC21, 🟪 Level0

#211 removed video toggle button
  index.html
  js/video.js
Labels: LGMSOC21, 🟪 Level0

#212 Footer content nicely placed
  Style.css
  index.html
Labels: LGMSOC21, 🟪 Level0

#213 Resolved details page submission bug
  Home.html
Labels: LGMSOC21, 🟨 Level2

#215 Footer redesign
  Home.html
  Style.css
  index.html
  login.html
  sign-up.html
Labels: LGMSOC21, 🟩 Level1

#234 Tech stack image updated
  README.md
Labels: LGMSOC21, 🟪 Level0

#276 district fetched- FormCorrection Page
  form-correction.html
Labels: LGMSOC21, 🟩 Level1
