Repository QAZIMAAZARSHAD/Voters-Registration-Portal, pull requests merged in 2021-07, with the labels that each got.

#301 Logo Folder Added
  Images/Logo/logo1.jpg
  Images/Logo/logo2.jpg
  Images/Logo/logo3.jpg
Labels: LGMSOC21, 🟩 Level1

#307 footer links addded
  Home.html
  forgetPass.html
  form-correction.html
  help.html
  login.html
  sign-up.html
Labels: LGMSOC21, 🟪 Level0

#318 Added submission successful page
  Home.html
  Images/bg.jpg
  Style.css
  submitted.css
  submitted.html
Labels: LGMSOC21, 🟨 Level2

#321 Flip logo
  Home.html
  Style.css
  forgetPass.html
  form-correction.html
  help.css
  help.html
  index.html
  login.html
  sign-up.html
Labels: LGMSOC21, 🟩 Level1

#352 Drop-Down List Commit
  Home.html
  feedbackform.html
  feedbackformsubmitted.html
  forgetPass.html
  form-correction.html
  help.html
  login.html
  sign-up.html
Labels: DCP21, 🟪 Level0

#355 Update pull_request_template.md
  .github/pull_request_template.md
Labels: DCP21, 🟪 Level0

#358 Removing checklist point from pull_request_template.md
  .github/pull_request_template.md
Labels: DCP21, 🟪 Level0

#401 Updated pull_request_template.md
  .github/pull_request_template.md
Labels: LGMSOC21, 🟪 Level0
